### ISSUE TITLE
Directories prioritized over files

### ISSUE THREAD

**Issue by dmfay** [niftylettuce/get-paths#2]
I'm using get-paths transitively through koa-views. My views directory contains a `users.pug` and a `users` directory with additional templates. Since get-paths only checks for files if no matching directory is found, an invocation of `getPaths('/absolute/path', 'users', 'pug')` resolves to `users/index.pug` instead of my `users.pug`.

It's probably better in my specific case if I just do what it expects, but I imagine there could be other instances in which that doesn't fit so well.

**Comment by niftylettuce** [comment]
Can you submit a pull request that fixes this issue along with a test perhaps?

**Comment by dmfay** [comment]
It might take me a bit to get to it but I'll see what I can do!

**Comment by niftylettuce** [comment]
would love your PR ❤️

**Comment by niksajanjic** [comment]
Wouldn't that fix be just changing the logic around from this:
```js
if (stats.isDirectory()) {
  // a directory
  return {
    rel: path.join(rel, `index.${ext}`),
    ext
  };
}
// a file
return { rel, ext: path.extname(rel).slice(1) };
```
to this:
```js
if (stats.isFile()) {
  // a file
  return { rel, ext: path.extname(rel).slice(1) };
}
// a directory
return {
  rel: path.join(rel, `index.${ext}`),
  ext
};
```

Not sure if we need to check whether it's directory or just assume it is when it's not a file?

**Comment by niftylettuce** [comment]
PR welcome - would love to have a test added for this too!
