### ISSUE TITLE
Remove the dependence of bluebird

### ISSUE THREAD

**Issue by brizer** [niftylettuce/get-paths#4]
This repo use bluebird only for promisify a callback function to a promise. And Node provider an API to do it https://nodejs.org/api/util.html#util_util_promisify_original.

**Comment by niftylettuce** [comment]
It wasn't added until 8.0 and this lib supports 6.0 https://github.com/niftylettuce/get-paths/blob/master/package.json#L39

**Comment by niftylettuce** [comment]
PR welcome with alternative fix though!

**Comment by niftylettuce** [comment]
one moment and i will release new version with this fixed

**Comment by niftylettuce** [comment]
Please install v0.0.5 of `get-paths` via `npm install get-paths@latest`.

This is also a dependency of `email-templates` and `koa-views`, and I am version bumping those packages right now as well.
