### ISSUE TITLE
Remove dependence of fs-extra

### ISSUE THREAD

**Issue by brizer** [niftylettuce/get-paths#5]
I found that fs-extra is not used. So it could be removed.

**Comment by niftylettuce** [comment]
Ty

**Comment by niftylettuce** [comment]
one moment and i will release new version with this fixed

**Comment by niftylettuce** [comment]
Please install v0.0.5 of `get-paths` via `npm install get-paths@latest`.

This is also a dependency of `email-templates` and `koa-views`, and I am version bumping those packages right now as well.
